### ISSUE TITLE
Bricked the BLE functionality of my dev board

### ISSUE THREAD

**Issue by Slappy2022** [openwch/ch583#22]
One of my dev boards has lost BLE functionality. I have a known-good elf that works on two of my three boards. Any advice on recovering the broken board? The non-BLE functionality appears to work fine. e.g. I can flash new code which shows that UART3 and GPIO_B4 can be operated. 

I'm guessing I flashed something that brought the board to a broken state. I've been unsuccessfully experimenting with adding rust bindings for BLE via the .a files, so I could have easily made a mistake.

**Comment by zerosensei** [comment]
Hi slappy,
The information you provided is too little, so I can't locate the problem.
What exactly do you mean by the loss of the BLE function? Is it unable to broadcast?
Have you tried downloading our BLE examples like [Peripheral](https://github.com/openwch/ch583/tree/main/EVT/EXAM/BLE/Peripheral)  to see if it functions normally?

**Comment by Slappy2022** [comment]
Thank you for the suggestion for use Peripheral. I was able to use BLE with the Peripheral. I was also able to install my other BLE code and successfully use BLE. Everything is now working as expected. 

I appreciate all the help. Cheers!
