### ISSUE TITLE
Bluetooth 5 Extended Advertisements

### ISSUE THREAD

**Issue by mikewen** [openwch/ch583#23]
How to broadcast Bluetooth Advertisements using coded 125kbps PHY?

The code here: https://github.com/openwch/ch583/blob/main/EVT/EXAM/BLE/SYNC_ADV/APP/broadcaster.c
use GAP_PHY_VAL_LE_1M

I couldn't find anywhere that define 125Kbps coded PHY.
Do you have an example?

Thank you very much!

**Comment by zerosensei** [comment]
it is defined here https://github.com/openwch/ch583/blob/6bd1b4685ec44519f3e49bdc47dda6a2ecaca7cc/EVT/EXAM/BLE/LIB/CH58xBLE_LIB.h#L886
```c
GAP_SetParamValue(TGAP_ADV_SECONDARY_PHY, GAP_PHY_VAL_LE_CODED);
```

**Comment by mikewen** [comment]
But how can I specify 125Kbps ?
I'd like to extend the range with low speed 125Kbps

**Comment by mikewen** [comment]
I see. I will try that. Thanks!!!
