### ISSUE TITLE
CTE extension on ch582

### ISSUE THREAD

**Issue by chegewara** [openwch/ch583#28]
Hi,
is CTE working on CH582/3, because i am having problems to enable it in `SYNC_ADV` example?

Thanks

**Comment by chegewara** [comment]
In theory it is enabled, because i can see proper event:
```
CH58x_BLE_LIB_V1.80
Initialized..    
Advertising..    
periodic enable..
CTE: GAPROLE_CONNECTIONLESS_CTE_ENABLE
```
but in practice it seems to be disabled, or WCH ble analyzer pro cant detect it:
![cte_flags](https://user-images.githubusercontent.com/1406020/222974573-fc241bd7-acd9-41ce-a553-53b714e0919a.jpg)

Flags is 0x69 and should be 0x6D to indicate CTEInfo data existing in payload.
![cte](https://user-images.githubusercontent.com/1406020/222975005-ca4e9372-80dc-4052-9233-a046fdcffb41.png)

**Comment by zerosensei** [comment]
Hi chegewara, 
the CTE Info field is reserved in AUX_ADV_IND: 
![image](https://user-images.githubusercontent.com/56950947/223000642-4ce06292-4310-4968-ae3b-e444baf5f1fe.png)
you can see the CTE Info is present in AUX_SYNC_IND: 
![image](https://user-images.githubusercontent.com/56950947/223000915-ef49e330-dd73-4c9b-b3da-b954a13dcfd7.png)
Here is an example of CTE configuration:
```c
uint8_t  cte_enable = TRUE;
uint8_t  cte_type = GAP_CTE_TYPE_AOD_2US;
uint8_t  cte_length = 10;
uint8_t  switch_pattern = 4;

GAP_SetParamValue( TGAP_CTE_TYPE,cte_type );
GAP_SetParamValue( TGAP_CTE_LENGTH,cte_length );
GAP_SetParamValue( TGAP_LENGTH_OF_SWITCHING_PATTERN,switch_pattern );
GAPRole_SetParameter(GAPROLE_CTE_CONNECTIONLESS_ENABLED, sizeof(uint8_t), &cte_enable); 
```
**However, the current version of the CH582 chip has a problem with this function, and it will be solved in the next chip version.**

**Comment by chegewara** [comment]
I found the same information in bluetooth specs after doing more research.
In my code i am only missing this line
```
GAP_SetParamValue( TGAP_LENGTH_OF_SWITCHING_PATTERN,switch_pattern );
```

Now i am trying to figure out why i cant catch `AUX_SYNC_IND` packets with ble analyzer pro.
I cant wait to get new ch582 or ch583 and to play a bit more with BLE5.x.

Thanks for help

**Comment by DeqingSun** [comment]
@zerosensei Thanks for sharing the information. Is there a CH58x version that can use the CTE feature flawlessly? If so how can we order it? Or is there another chip model that just work?

**Comment by DeqingSun** [comment]
> I found the same information in bluetooth specs after doing more research. In my code i am only missing this line
> 
> ```
> GAP_SetParamValue( TGAP_LENGTH_OF_SWITCHING_PATTERN,switch_pattern );
> ```
> 
> Now i am trying to figure out why i cant catch `AUX_SYNC_IND` packets with ble analyzer pro. I cant wait to get new ch582 or ch583 and to play a bit more with BLE5.x.
> 
> Thanks for help

@chegewara Would you mind sharing if you got the CTE working?
