### ISSUE TITLE
Schematic for CH582F

### ISSUE THREAD

**Issue by happytm** [openwch/ch583#30]
I am planning to design a project based on CH582F. I tried to find evaluation board for 28 pin chip but could not find one.

Do you have reference schematic somewhere?

Thanks.

**Comment by zerosensei** [comment]
The peripheral components of CH582F are the same as those of CH583M, so you can refer to the [schematic diagram of CH583M](https://github.com/openwch/ch583/blob/aaa5f9839cefc3794bc8391f0207fc1568ddeb18/EVT/PUB/CH583SCH.PDF).
In addition, if you need the package diagram of CH582F, you can download it [here](https://www.wch.cn/downloads/SCHPCB_ZIP.html).
