### ISSUE TITLE
CH582M Wont enter bootloader download mode anymore (exam BLE/HID_Keyboard)

### ISSUE THREAD

**Issue by anaszulkifli** [openwch/ch583#32]
Hi, I tried the Exam/BLE/HID_Keyboard program and downloaded to my CH582M. I changed the parameter of DL Config Pin from PB22 to PB11 and now I can no longer enter bootloader download mode using BOOT button + connecting USB-C and WCHISP tool wont find the device.

The program will start and typing "abcdefg...xyzabc..." once connected to bluetooth HID_Keyboard and reset button only reset the program typing back to "abc...".

Is there anyway for me to enter bootloader/download mode again? Button combination or shorting certain pins?

**Comment by aleph-five** [comment]
If I am right, you should connect pin PB11 to ground and connect your device to usb

**Comment by anaszulkifli** [comment]
I have tried it, shorting GND to Pin 11 but still it will continue to boot into the example app instead of bootloader. Can I enter bootloader via UART TTL COM connection instead?

**Comment by andelf** [comment]
Ref: https://github.com/ch32-rs/wchisp/blob/4b4787243ef9bc87cbbb0d95c7482b4f7c9838f1/devices/0x16-CH58x.yaml#L61-L66

**Comment by anaszulkifli** [comment]
> Ref: https://github.com/ch32-rs/wchisp/blob/4b4787243ef9bc87cbbb0d95c7482b4f7c9838f1/devices/0x16-CH58x.yaml#L61-L66

The setting seems it can be toggled on/off but I cant get wchisp to even detect the device. The device will boot into the app directly and start typing "abcdefghijk..."

**Comment by anaszulkifli** [comment]
Solved:

Got myself serial usb rx-tx and used No-Key serial port w/ DL key back to PB22 + 115200 baud.

Played around with DL ready <wait for device> on the tool to reset, connect PA9 PA8 first, then GND finally 3V3.

Once reset, connect via serial on device like before it will say not recognized, but just keep pressing Download until it starts downloading.

Guide here:
https://www.cnblogs.com/gscw/p/16034836.html
