### ISSUE TITLE
Information Request: BLE & USB certifications

### ISSUE THREAD

**Issue by limpkin** [openwch/ch583#9]
Hello!

That IC just looks wonderful, congrats!
Next step obviously is to embed it into commercial products. However, I was wondering if any certification was passed regarding the USB & Bluetooth transceivers?

**Comment by zerosensei** [comment]
The Bluetooth transceiver has passed the Bluetooth SIG product certification, Declaration ID: [D058185](https://launchstudio.bluetooth.com/ListingDetails/142898).
And the USB transceiver can pass USB-IF.
